language: objective-c
before_install:
- gem install xcpretty -N cocoapods
script:
- set -o pipefail
- cd Support
- xcodebuild -project ApplicationInsights.xcodeproj -scheme "ApplicationInsightsOSX"
  -configuration Release -destination "platform=OS X" test | xcpretty -c
