language: objective-c

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild -project Support/ApplicationInsights.xcodeproj -scheme ApplicationInsightsOSX -configuration Release -destination "platform=OS X" XCODEBUILD_GCC_PREPROCESSOR_DEFINITIONS="CI=1" test | xcpretty -c